[package]
name = "jarvis-cocoon"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
jarvis-common = { path = "../jarvis-common" }
jarvis-shield = { path = "../jarvis-shield" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
sha2.workspace = true
glob.workspace = true
parking_lot.workspace = true
