[package]
name = "jarvis-biometrics"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
jarvis-common = { path = "../jarvis-common" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace = true
sha2.workspace = true
